she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('<int:pk>/edit', views.EditStoryView.as_view(), name='editStory'),
    path('add-story/', views.AddStoryView.as_view(),name='newStory'),
    path('<int:pk>/delete', views.DeleteStoryView.as_view(), name='deleteStory'),
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import include, path
# below 090222
# from users import views
# from users.views import ProfileView

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    
]

she_codes_news/users/urls.py
from django.urls import path
from .views import CreateAccountView, ProfileView
from . import views

app_name = 'users'

urlpatterns = [
    path('create-account/', CreateAccountView.as_view(), name='createAccount'),
    # view user profile
    path('<int:pk>/', ProfileView.as_view(), name='profile'),
    # Below: edit user profile
    path('<int:pk>/update', views.UpdateProfileView.as_view(), name='updateProfile') 
]

she_codes_news/news/models.py
from django.contrib.auth import get_user_model
from django.db import models


class NewsStory(models.Model):
    title = models.CharField(max_length=200)
    # author = models.CharField(max_length=200)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )
    pub_date = models.DateTimeField()
    content = models.TextField()
    image = models.URLField(null = True, blank = True)
    # picture = models.UrlField(upload_to=settings.MEDIA_ROOT)

she_codes_news/users/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser 
from django.contrib.auth.models import User
from django.urls import reverse

from django.contrib.auth import get_user_model
from django.db import models


class CustomUser(AbstractUser):

    about_me = models.TextField(blank=True)

    image = models.URLField(null = True, blank = True)
    
    def __str__(self):
        return self.username
    
    def get_absolute_url(self):
        return reverse('users:profile', kwargs={'pk': self.pk})



# class Post(models.Model):
#         text = models.CharField(max_length=200)
#         posti = models.ImageField(upload_to='media/images', null=True, blank="True")
#         user = models.ForeignKey(User, related_name='imageuser', on_delete=models.CASCADE, default=2)

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewsStory

class StoryForm(ModelForm):
    class Meta:
        model = NewsStory
        fields= ['title', 'pub_date', 'content', 'image']
        # BELOW: ADDING A PICKER WIDGET
        widgets = {'pub_date': forms.DateInput(format=('%m/%d/%Y'),
        attrs = {'class':'form-control', 'placeholder':'Select a date','type':'date'}),
        }

she_codes_news/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser
from django.forms import ModelForm
 
class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'about_me', 'image']
        
class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ['email', 'about_me', 'image']

she_codes_news/news/views.py
from dataclasses import fields
from django.views import generic
from .models import NewsStory

# BELOW: FORM TUTORIAL IMPORTS
from django.urls import reverse_lazy, reverse
from .forms import StoryForm
from django.core.exceptions import PermissionDenied



class IndexView(generic.ListView):
    template_name = 'news/index.html'

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.all()[:4]
        context['all_stories'] = NewsStory.objects.all()
        return context

class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'

# form class
class AddStoryView(generic.CreateView):
    form_class = StoryForm
    context_object_name = 'storyForm'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class EditStoryView(generic.UpdateView):
    model = NewsStory
    template_name = 'news/createStory.html'
    fields = ['title', 'image', 'content']
    
    def get_success_url(self):
        story_id = self.object.id
        return reverse('news:story', kwargs={'pk': story_id})

    def get_object(self, queryset = None):
        story= super().get_object(queryset)
        if story.author != self.request.user:
            raise PermissionDenied
        return story
    
# to delete story make new template. edit sotry use existing.
class DeleteStoryView(generic.DeleteView):
    model = NewsStory
    template_name = 'news/deleteStory.html'
    success_url = reverse_lazy('news:index')

    def get_object(self, queryset = None):
        story= super().get_object(queryset)
        if story.author != self.request.user:
            raise PermissionDenied
        return story
        

she_codes_news/users/views.py
from cProfile import Profile
# from multiprocessing import context
from django.shortcuts import render

from django.urls import reverse_lazy, reverse
from django.core.exceptions import PermissionDenied

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views import generic
from .models import CustomUser
from .forms import CustomUserCreationForm, CustomUserChangeForm

# view user profile
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.forms import UserCreationForm 
from django.contrib.auth.mixins import LoginRequiredMixin

# importing NewsStory model from news directory
from news.models import NewsStory

from django.urls import reverse_lazy
from django.views.generic.edit import CreateView 
from django.views import generic
from .models import CustomUser
from django.core.exceptions import PermissionDenied

class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/createAccount.html'

    # def saveImage(request):
    #     if request.method == "POST":
    #         image = request.FILES.get('image')
    #         new_image = <Image_Model>.objects.create(image = image
    #     )

    #     return redirect('/somewhere/')
    # return render(request, 'new_image.html',)
    

# class EditAccountView():
#     form_class = UserCha
#     success_url = reverse_lazy('login')
#     template_name = 'users/createAccount.html'

class ProfileView(LoginRequiredMixin, DetailView):
    model = CustomUser
    template_name = 'users/userProfile.html'
    context_object_name = 'user'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['all_stories'] = NewsStory.objects.filter(author=self.kwargs['pk'])
        context['user_stories'] = NewsStory.objects.filter(author=self.kwargs['pk'])
        return context
    
   

class UpdateProfileView(generic.UpdateView):
    model = CustomUser
    form_class = CustomUserChangeForm
    context_object_name = 'userForm'
    template_name = 'users/updateProfile.html'
    # fields = ['email', 'about_me', 'image']

    def get_object(self, queryset=None):
        return self.request.user

    # def get_success_url(self):
    #     user_id = self.object.id
    #     return reverse('user:profile', kwargs={'pk': user_id})

    # def get_object(self, queryset = None):
    #     profile= super().get_object(queryset)
    #     if profile != self.request.user:
    #         raise PermissionDenied
    #     return profile

she_codes_news/news/templates/news/createStory.html
{% extends "base.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit">
</form>
{% endblock %}

she_codes_news/news/templates/news/deleteStory.html
{% extends "base.html" %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <p class="update_warning"> &#9888; Are you sure you want to delete "{{ object }}"? 
        <br/>Deleted stories cannot be recovered.</p>
    {{ form.as_p }}
    <input type="submit" value="Confirm">
</form>
{% endblock %}

she_codes_news/news/templates/news/index.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

    <h2 >Latest News</h2>
    <div>
        <div id="latest-stories">
            {% if latest_stories %}
                {% for story in latest_stories %}
                    {% comment %} <p>{{ story.title }}</p> {% endcomment %}
                    {%include "./storyCard.html" with story=story position=forloop.counter %}
                {% endfor %}
            {% else %}
                <p>No stories are available.</p>
            {% endif %}
        </div>
        <br/>
        <div id="all-stories">
            {% if latest_stories %}
                {% for story in all_stories %}
                    {% comment %} <p>{{ story.title }}</p> {% endcomment %}
                    {% include "./storyCard.html" with story=story %}
                {% endfor %}
            {% else %}
                <p>No stories are available.</p>
            {% endif %}
        </div>  
    </div>
    <a href="{% url 'news:newStory' %}">Write New Story</a>
    <a href="{% url 'users:createAccount' %}">Create Account</a>

{% endblock %}

she_codes_news/news/templates/news/story.html
{% extends "base.html" %}
{% load static %}
{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}
{% block content %}

<div id="story-wrapper">
    <h2 class="storycard_heading">{{ story.title }}</h2>
    <h4><a href="{% url 'users:profile' pk=story.author.id %}">Written by: {{ story.author }}</a></h4>
    <h4>Date Submitted: {{story.pub_date}}</h4>
    <div id="story-content">
        {% if story.image%}
            <img src="{{ story.image }}">
        {% else %}
            <img src="https://picsum.photos/600">
        {% endif %}
    {{ story.content|linebreaks }}
    </div>
    <a href="{% url 'news:deleteStory' story.id %}">Delete Story</a>
</div>

{% endblock %}

she_codes_news/news/templates/news/storyCard.html
<div class="story-card" id="story-card-{{ position }}">
    <a href="{% url 'news:story' story.id %}">
        {% comment %} {% if position < 5 %}
            <img src="../static/news/images/placeholder-{{ position }}.jpg"> {% endcomment %}
        {% if story.image%}
            <img src="{{ story.image }}">
        {% else %}
            <img src="https://picsum.photos/600">
        {% endif %}
        <div class="box">
        <div class="story-card-text">
            <h3>{{ story.title }}</h3>
            <h4>{{ story.author }}</h4>
            <h4>{{ story.pub_date }}</h4>
        </div>
        </div>
    </a>
</div>

she_codes_news/templates/base.html
{% load static %}
<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>She Codes News</title>
        <meta name="description" content="">
        <meta name="author" content="Ayeesha Fredericksen">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        {% block stylesheets %}{% endblock %}
    </head>

    <body class="header_container">
        <header style="bottom-border: 5px groove #orange;">
            <div id="header-text">
                <a id="header-link" href="{% url 'news:index' %}">
                    <h1><img style="width:150px; display:inline-block;" src="/static/news/images/Shecodesbymidnight.png" alt="shecodes logo">
                        <span style="color: #8643c4;">She</span><span style="color: orange;">{Codes}</span> By Midnight</h1>
                    <h2>A news page where all stories are published at midnight<span style="font-size: 1.5rem; font-style: italic;"> - (totally not because I ran out of time to override the date-time selector)</span></h2>
                    {% comment %} <h3>(totally not because I couldn't get the time change to work)</h3> {% endcomment %}
                </a>
            </div>
            <!-- include nav here -->
            {% include './nav.html' %}
        </header>
        
        <!-- content blocks here -->
        {% block content %}{% endblock %}

    </body>
</html>

she_codes_news/templates/nav.html
<!-- <nav>
    <a href="{% url 'news:index' %}">Home</a>
    <a href="#">username</a>
    <a href="#">Logout</a>
    <a href="#">Login</a>
</nav> -->

<nav class="nav">
    <a href="{% url 'news:index' %}">Newspage Home</a><br/>
    <a href="https://shecodes.com.au/"><span style="color: #8643c4;">She</span><span style="color: orange;">Codes</span> Website</a><br/>
    {% if request.user.is_authenticated %}
        {% comment %} <a href="{% url 'users:userProfile' %}">{{ user.username }}</a> {% endcomment %}
        <a href="{% url 'users:profile' request.user.id %}">Current User: {{ request.user.username }}</a><br/>
        <a href="{% url 'logout' %}">Logout</a>
    {% else %}
        <a href="{% url 'login' %}">Login</a>
    {% endif %}
    <br/>
    <a href="{% url 'users:createAccount' %}">Create Account</a>
</nav>

she_codes_news/users/templates/users/createAccount.html
{% extends 'base.html' %}
{% block content %}
<h2>Create Account</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create Account</button>
</form>
{% endblock %}

she_codes_news/users/templates/users/updateProfile.html
{% extends 'base.html' %}

{% block content %} 
<h2>Update account</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    {% comment %} <input type="submit" value="Confirm"> {% endcomment %}
    <button type="submit">Save my profile changes</button>
    <br/>
    <p class=""> &#9888; Click Wisely - Once you save your changes they cannot be undone!</p>
</form>
{% endblock %} 

she_codes_news/users/templates/users/userProfile.html
{% extends 'base.html' %}
{% block content %}
{% comment %} <div id="w"> {% endcomment %}
<div id="content">

    <div>
        <div class="circular--landscape">
            {% if user.image%}
                    <img src="{{ user.image }}">
                {% else %}
                    <img src="https://picsum.photos/600">
            {% endif %}
            </div>
        <h2>Welcome to the profile of <span style="color: orange;">{{user.username}}</span> </h2>
    </div>

    <div>
        <p><strong>About Me:</strong>&nbsp{{user.about_me}}</p>
    </div>


    <div>
        {% if profile == profile.id %}
            <a href="{% url 'users:updateProfile' user.id %}">Edit Profile</a>
        {% endif %} 
    </div>


    <div class="storylist">
        <h4>My Stories:</h4>
        {% for story in user.newsstory_set.all %}
            <ul>
                <a href="{% url 'news:story' story.id %}">{{story.title}}</a></p> 
            <div class="edit_del_container"> 
                <a class="edit_container" href="{%url 'news:editStory' story.id %}"> Edit </a> / <a class="del_container" href="{%url 'news:deleteStory' story.id %}"> Delete </a>
            </div>
            </ul>
        {% empty %}
            <p>No stories are available.</p>
        {% endfor %}
        
    </div>


    <div>
        <a  href="{% url 'news:newStory' %}">Write a new Story</a>
    </div>

</div>

{% endblock %}